<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="77797" started-at="2016-09-02T09:01:14Z" finished-at="2016-09-02T09:02:32Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="77797" started-at="2016-09-02T09:01:14Z" finished-at="2016-09-02T09:02:32Z">
      <class name="com.execute.project.PageObjectTest">
        <test-method status="PASS" signature="intializeDriver()[pri:0, instance:com.execute.project.PageObjectTest@704f66ab]" name="intializeDriver" is-config="true" duration-ms="2666" started-at="2016-09-02T14:31:14Z" finished-at="2016-09-02T14:31:16Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- intializeDriver -->
        <test-method status="FAIL" signature="executeTest1()[pri:0, instance:com.execute.project.PageObjectTest@704f66ab]" name="executeTest1" duration-ms="73873" started-at="2016-09-02T14:31:16Z" finished-at="2016-09-02T14:32:30Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The redefine chkbox is not selected expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The redefine chkbox is not selected expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.selenium.finale.RodanFieldTest.verifychkRedefine(RodanFieldTest.java:130)
	at com.execute.project.PageObjectTest.executeTest1(PageObjectTest.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- executeTest1 -->
        <test-method status="PASS" signature="CloseBrowser()[pri:0, instance:com.execute.project.PageObjectTest@704f66ab]" name="CloseBrowser" is-config="true" duration-ms="1240" started-at="2016-09-02T14:32:30Z" finished-at="2016-09-02T14:32:32Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CloseBrowser -->
      </class> <!-- com.execute.project.PageObjectTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
